
/* ------------------------------------------------------------
 * Filename ............... Version.Hpp
 *
 * General Purpose ........ General version information
 * ------------------------------------------------------------
 * First date ............. 12-07-94 11:05am
 *
 * First in version ....... 2.00
 *
 * Written by ............. Alain Schellinck
 *
 * Copyright .............. Nephilim software development
 * ------------------------------------------------------------
 * Revisions:
 * ----------
 *
 *   Date   | By |                  Purpose                   |
 * ---------+----+--------------------------------------------+
 *          |    |                                            |
 *          |    |                                            |
 *          |    |                                            |
 */

/*-------------------------------------------------------------------------*/

#ifndef __VERSION_HPP
#  define __VERSION_HPP

/*-------------------------------------------------------------------------*/

#define  projectCode       "TE"
#define  projectName       "TheEdit"
#define  protectKey        "scdEtvheiTArtanosEeddedagiMe"
#define  projectSpec       "ProBoard advanced full screen message editor"
#define  versionText       "2.10á2"
#define  copyrightYear     "1994, 1995"
#define  author            "Alain Schellinck"
#define  home_bbs          "The Happy House"

/*-------------------------------------------------------------------------*/

#endif                                 // __VERSION_HPP

/*---------------------------] END OF THE CODE [---------------------------*/
