
October 7, 1996

Dear Don,

Thank you for registering ProBoard!  [Current version is 2.15]

I know that you will enjoy it now and in the future as the new
enhancements come out.

YOUR PROBOARD REGISTRATION CHARGE WILL APPEAR ON YOUR STATEMENT AS BEING
MADE BY JOYCE AND ASSOCIATES.

To install your 2.15 key for ProBoard, copy the REGKEY.PB file into the
SYSTEM subdirectory - typically C:\PB.  Then double check PROCFG for
the following settings (must be EXACT):

ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³                    Sysop Name:  Don Pryor                                  ³
³                    BBS Name  :  Wichita BBS                                ³
ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

With your key file installed:

1.  The shareware message on startup and in the logfile have been
    eliminated.
2.  Your Echomail messages will now display the tearline:
    ---ProBoard v2.15[Reg]
3.  You can now specify different subdirectories for Uploaded files

If you have any questions or comments, feel free to contact me either
Netmail, my BBS, or write to me:

Ken Givens
2735 Stemmons Fwy
Dallas, Tx 75052
USA

We also have a PROBOARD National Echo setup to discuss ProBoard related
topics, questions, comments, etc.  Please ask your local Fido sysop to
carry it, or you can access it on The Chess Board.

There are quite a few good ProBoard utilities out there, call my BBS and
download any of them you wish!  You'll find everything in the "ProBoard
files", "Proboard PEX" and "Proboard DQP" sections.  You can also FREQ "PBFILES"
if you are using a mailer package.

The Chess Board (214-641-1136) : 1200-28800 bps : V.34b : Fidonet 1:124/2213
kgivens@whytel.com - http://www.whytel.com/users/kgivens

